### ISSUE TITLE
Getting error initializing Iconv on Ruby 2.6.0

### ISSUE THREAD

**Issue by jasonperrone** [ruby/iconv#15]
2.6.0 :001 > Iconv.new('UTF-8//IGNORE','UTF-8')
Traceback (most recent call last):
ArgumentError (cannot set encoding on non-encoding capable object)

**Comment by andy-ganchrow** [comment]
@jasonperrone try this

@ic = Iconv.new('utf8//ignore', 'utf8')

**Comment by jasonperrone** [comment]
Interesting. Thanks, Andy. Any chance I could grab a sentence or two explanation? ;-)

**Comment by andy-ganchrow** [comment]
Still working on an explanation to be honest ;)

**Comment by andy-ganchrow** [comment]
@ic = Iconv.new('UTF-8//IGNORE', 'UTF-8')

Works in ruby 2.6.0 preview1 and 2, does not in preview3 and greater, so the commit is between preview2 and preview3

**Comment by jasonperrone** [comment]
Good job bisecting that.

**Comment by nurse** [comment]
Thank you for reporting!
I fixed it by 1c1a2c5 and released v1.0.6!

**Comment by jasonperrone** [comment]
Thank you!

**Comment by andy-ganchrow** [comment]
Thanks !!
