### ISSUE TITLE
How to install on Windows 7?

### ISSUE THREAD

**Issue by alexandre-mbm** [ruby/iconv#8]
```
C:\> ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
```

**Comment by lijunhaos** [comment]
![1497604573 1](https://user-images.githubusercontent.com/21354698/27220383-85e04570-52b7-11e7-897c-fc9f1585747a.jpg)

**Comment by nurse** [comment]
You need to install libiconv by some way and specify `--with-iconv-dir=/somewhere`.
